INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Alaska', N'AK', N'West')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Alabama', N'AL', N'South')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Arkansas', N'AR', N'South')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Arizona', N'AZ', N'West')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'California', N'CA', N'West')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Colorado', N'CO', N'West')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Connecticut', N'CT', N'Northeast')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Delaware', N'DE', N'Northeast')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Florida', N'FL', N'South')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Georgia', N'GA', N'South')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Hawaii', N'HI', N'West')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Iowa', N'IA', N'Midwest')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Idaho', N'ID', N'West')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Illinois', N'IL', N'Midwest')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Indiana', N'IN', N'Midwest')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Kansas', N'KS', N'Midwest')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Kentucky', N'KY', N'South')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Louisiana', N'LA', N'South')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Massachusetts', N'MA', N'Northeast')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Maryland', N'MD', N'Northeast')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Maine', N'ME', N'Northeast')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Michigan', N'MI', N'Midwest')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Minnesota', N'MN', N'Midwest')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Missouri', N'MO', N'Midwest')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Mississippi', N'MS', N'South')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Montana', N'MT', N'West')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'North Carolina', N'NC', N'South')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'North Dakota', N'ND', N'Midwest')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Nebraska', N'NE', N'Midwest')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'New Hampshire', N'NH', N'Northeast')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'New Jersey', N'NJ', N'Northeast')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'New Mexico', N'NM', N'West')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Nevada', N'NV', N'West')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'New York', N'NY', N'Northeast')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Ohio', N'OH', N'Midwest')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Oklahoma', N'OK', N'South')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Oregon', N'OR', N'West')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Pennsylvania', N'PA', N'Northeast')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Rhode Island', N'RI', N'Northeast')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'South Carolina', N'SC', N'South')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'South Dakota', N'SD', N'Midwest')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Tennessee', N'TN', N'South')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Texas', N'TX', N'South')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Utah', N'UT', N'West')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Virginia', N'VA', N'South')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Vermont', N'VT', N'Northeast')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Washington', N'WA', N'West')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Wisconsin', N'WI', N'Midwest')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'West Virginia', N'WV', N'South')
INSERT INTO [dbo].[List_US_State] ([State], [StateAbbr], [Region]) VALUES (N'Wyoming ', N'WY', N'West')
