-- Source: https://en.wikipedia.org/wiki/Vehicle_identification_number
CREATE VIEW MakeView
AS
SELECT 'AAV' AS [WMI],'South Africa' AS [Country],'Volkswagen' AS [Make]
UNION SELECT 'AFA','South Africa','Ford'
UNION SELECT 'JA','Japan','Isuzu'
UNION SELECT 'JF','Japan','Fuji'
UNION SELECT 'JH','Japan','Honda'
UNION SELECT 'JMB','Japan','Mitsubishi'
UNION SELECT 'JMZ','Japan','Mazda'
UNION SELECT 'JN','Japan','Nissan'
UNION SELECT 'JS','Japan','Suzuki'
UNION SELECT 'JT','Japan','Toyota'
UNION SELECT 'KL','South Korea','Daewoo'
UNION SELECT 'KMH','South Korea','Hyundai'
UNION SELECT 'KN','South Korea','Kia'
UNION SELECT 'KPT','South Korea','SsangYong'
UNION SELECT 'SAJ','United Kingdom','Jaguar'
UNION SELECT 'SAL','United Kingdom','Land Rover'
UNION SELECT 'SAR','United Kingdom','Rover'
UNION SELECT 'SCC','United Kingdom','Lotus Cars'
UNION SELECT 'SCE','Ireland','DeLorean'
UNION SELECT 'TCC','Switzerland','SMART'
UNION SELECT 'TMA','Czech Republic','Hyundai'
UNION SELECT 'TMB','Czech Republic','Škoda'
UNION SELECT 'TRU','Hungary','Audi'
UNION SELECT 'UU','Romania','Dacia'
UNION SELECT 'VA0','Austria','ÖAF'
UNION SELECT 'VF1','France','Renault'
UNION SELECT 'VF3','France','Peugeot'
UNION SELECT 'VF6','France','Volvo'
UNION SELECT 'VF7','France','Citroën'
UNION SELECT 'VFE','France','Iveco'
UNION SELECT 'VSS','Spain','SEAT'
UNION SELECT 'VV9','Spain','Tauro'
UNION SELECT 'WAU','Germany','Audi'
UNION SELECT 'WAP','Germany','Alpina'
UNION SELECT 'WBA','Germany','BMW'
UNION SELECT 'WBS','Germany','BMW'
UNION SELECT 'WDB','Germany','Mercedes-Benz'
UNION SELECT 'WDC','Germany','Daimler'
UNION SELECT 'WDD','Germany','Daimler'
UNION SELECT 'WMX','Germany','Daimler'
UNION SELECT 'WEB','Germany','EvoBus'
UNION SELECT 'WF0','Germany','Ford'
UNION SELECT 'WJM','Germany','Iveco'
UNION SELECT 'WJR','Germany','Irmscher'
UNION SELECT 'WKK','Germany','Kässbohrer'
UNION SELECT 'WMA','Germany','MAN'
UNION SELECT 'WME','Germany','Smart'
UNION SELECT 'WMW','Germany','Mini'
UNION SELECT 'WP0','Germany','Porsche'
UNION SELECT 'WP1','Germany','Porsche'
UNION SELECT 'WUA','Germany','Quattro'
UNION SELECT 'WVG','Germany','Volkswagen'
UNION SELECT 'WVW','Germany','Volkswagen'
UNION SELECT 'WV1','Germany','Volkswagen'
UNION SELECT 'WV2','Germany','Volkswagen'
UNION SELECT 'W0L','Germany','Opel'
UNION SELECT 'W0SV','Germany','Opel'
UNION SELECT 'YK1','Finland','Saab'
UNION SELECT 'YS3','Sweden','Saab'
UNION SELECT 'YTN','Sweden','Saab'
UNION SELECT 'YV1','Sweden','Volvo Cars'
UNION SELECT 'ZAM','Italy','Maserati'
UNION SELECT 'ZAR','Italy','Alfa Romeo'
UNION SELECT 'ZCF','Italy','Iveco'
UNION SELECT 'ZFA','Italy','Fiat'
UNION SELECT 'ZFF','Italy','Ferrari'
UNION SELECT 'ZGA','Italy','Iveco'
UNION SELECT 'ZHW','Italy','Lamborghini'
UNION SELECT 'ZLA','Italy','Lancia'
UNION SELECT '1C','United States','Chrysler'
UNION SELECT '1F','United States','Ford'
UNION SELECT '1G','United States','General Motors'
UNION SELECT '1G3','United States','Oldsmobile'
UNION SELECT '1GC','United States','Chevrolet'
UNION SELECT '1GM','United States','Pontiac'
UNION SELECT '1H','United States','Honda'
UNION SELECT '1J','United States','Jeep'
UNION SELECT '1L','United States','Lincoln'
UNION SELECT '1M','United States','Mercury'
UNION SELECT '1N','United States','Nissan'
UNION SELECT '1VW','United States','Volkswagen'
UNION SELECT '1YV','United States','Mazda'
UNION SELECT '2F','Canada','Ford'
UNION SELECT '2G','Canada','General Motors'
UNION SELECT '2G1','Canada','Chevrolet'
UNION SELECT '2G2','Canada','Pontiac'
UNION SELECT '2H','Canada','Honda'
UNION SELECT '2HM','Canada','Hyundai'
UNION SELECT '2M','Canada','Mercury'
UNION SELECT '2T','Canada','Toyota'
UNION SELECT '3F','Mexico','Ford'
UNION SELECT '3G','Mexico','General Motors'
UNION SELECT '3H','Mexico','Honda'
UNION SELECT '3N','Mexico','Nissan'
UNION SELECT '3VW','Mexico','Volkswagen'
UNION SELECT '4F','United States','Mazda'
UNION SELECT '4J','United States','Mercedes-Benz'
UNION SELECT '4M','United States','Mercury'
UNION SELECT '4S','United States','Subaru'
UNION SELECT '4T','United States','Toyota'
UNION SELECT '4US','United States','BMW'
UNION SELECT '5F','United States','Honda'
UNION SELECT '5L','United States','Lincoln'
UNION SELECT '5T','United States','Toyota'
UNION SELECT '5YJ','United States','Tesla'
UNION SELECT '6F','Australia','Ford'
UNION SELECT '6G','Australia','General Motors'
UNION SELECT '6G1','Australia','Chevrolet'
UNION SELECT '6G2','Australia','Pontiac'
UNION SELECT '6H','Australia','Holden'
UNION SELECT '6MM','Australia','Mitsubishi'
UNION SELECT '6T1','Australia','Toyota'
UNION SELECT '8AP','Argentina','Fiat'
UNION SELECT '8AT','Argentina','Iveco'
UNION SELECT '9BD','Brazil','Fiat'
UNION SELECT '9BW','Brazil','Volkswagen'
UNION SELECT '93H','Brazil','Honda'
UNION SELECT '93W','Brazil','Fiat'
UNION SELECT '93Z','Brazil','Iveco'
UNION SELECT '9BH','Brazil','Hyundai'